name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel Action (dae-governor)
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          PRODUCTION: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DAE_GOVERNOR }}
